### ISSUE TITLE
GHA unable to find repo as written in docs

### ISSUE THREAD

**Issue by KurtLehnardt** [managemy-lease/action-aws-ses-template-uploader#3]
GHA is unable to find managemy-lease/ses-template-uploader@v1 with the error `Error: Unable to resolve actions. Repository not found: managemy-lease/ses-template-uploader.`

replacing it with managemy-lease/action-aws-ses-template-uploader@v1 works

**Comment by MylesDev** [comment]
Resolved. Thank you for raising & sorry for the delay.
